### ISSUE TITLE
Add functions like logarithms and trigonometric function

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/calc#1]
# Problem
The user is restricted to a fairly basic set of math operations: generally infix functions and some suffix functions (through the special characters ² and ³). 

# Solution
Introduce `log` and the trigonometric functions: at least sine, cosine, tan, and their inverses.
- `log` can start out as log base 10 but we can expand it to either take in a variable number of parameters or give the ability to specify a `logN` syntax. WE could also add `ln` of course
- What matters more is extending the syntax to support these functions versus what's actually implemented.

**Comment by xTibor** [comment]
After implementing those functions above it would also be useful to introduce some math constants like `pi` and `tau` for the trigonometric functions.

**Comment by huntergoldstein** [comment]
That would be very useful, I agree. What will probably happen is implementing #2 and having a "batteries included" configuration that has the above and useful constants defined: `pi`, `tau`, `e`, etc.
