### ISSUE TITLE
Expose Environment trait

### ISSUE THREAD

**Issue by Refefer** [redox-os/calc#19]
Quite simply, could we expose the Environment trait from the library?  This could be quite the useful library if we could implement our own!

**Comment by huntergoldstein** [comment]
Yeah that was sort of the point; my b.

**Comment by huntergoldstein** [comment]
Should be fixed as of 9e7dd998037412ffa9019316502c07a64fd0c34e :tada:

**Comment by Refefer** [comment]
Great, thanks!
